"""fresh start

Revision ID: 7d10a3f3bd8f
Revises: 
Create Date: 2025-10-18 00:48:48.663952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d10a3f3bd8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        # Drop existing column and recreate as UUID
        batch_op.drop_column('checked_in_by')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        # Recreate column as UUID
        batch_op.add_column(sa.Column('checked_in_by', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['checked_in_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('checked_in_by')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        # Recreate as VARCHAR
        batch_op.add_column(sa.Column('checked_in_by', sa.VARCHAR(length=36), nullable=True))

    # ### end Alembic commands ###
